name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: yarn

    - name: test
      run: yarn test
      
    - name: build
      run: yarn build:prod
      
    - name: deploy
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: yarn deploy
